export declare const EVENT_TYPES: readonly ["session_started", "assistant_delta", "assistant_message", "tool_call_started", "tool_call_completed", "approval_required", "approval_resolved", "session_status_changed", "session_result", "session_error", "user_message"];
export type EventType = (typeof EVENT_TYPES)[number];
export declare const SESSION_STATUSES: readonly ["queued", "running", "completed", "failed", "cancelled"];
export type SessionStatus = (typeof SESSION_STATUSES)[number];
export declare const VALID_TRANSITIONS: Readonly<Record<SessionStatus, readonly SessionStatus[]>>;
export declare const PROVIDERS: readonly ["claude", "book", "openclaw"];
export type Provider = (typeof PROVIDERS)[number];
export declare const ERROR_CODES: readonly ["unauthenticated", "forbidden", "not_found", "invalid_request", "state_conflict", "host_offline", "provider_unreachable", "directory_not_found", "session_not_resumable", "command_timeout", "seq_gap_detected"];
export type ErrorCode = (typeof ERROR_CODES)[number];
export declare const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>>;
